"""
Demo: File Handling

Demonstrates:
- Uploading CSV, TXT, and JSON files
- Previewing uploaded content
- Generating and downloading files from within the app
"""

import json
from datetime import datetime

import pandas as pd
import streamlit as st


def render():
    st.header("📂 File Handling")
    st.markdown(
        "Upload files into the app and download generated outputs — "
        "a common pattern in data-processing dashboards."
    )

    upload_tab, download_tab = st.tabs(["⬆️ Upload", "⬇️ Download"])

    # ── Upload ───────────────────────────────────────────────────────────
    with upload_tab:
        st.subheader("Upload a File")
        uploaded = st.file_uploader(
            "Choose a file",
            type=["csv", "txt", "json"],
            help="Supported formats: CSV, TXT, JSON",
        )

        if uploaded is not None:
            st.success(f"Uploaded **{uploaded.name}** ({uploaded.size:,} bytes)")
            file_ext = uploaded.name.rsplit(".", 1)[-1].lower()

            if file_ext == "csv":
                df = pd.read_csv(uploaded)
                st.markdown(f"**Shape:** {df.shape[0]} rows × {df.shape[1]} columns")
                st.dataframe(df, use_container_width=True)

            elif file_ext == "json":
                try:
                    data = json.load(uploaded)
                    if isinstance(data, list):
                        df = pd.DataFrame(data)
                        st.markdown(
                            f"**Shape:** {df.shape[0]} rows × {df.shape[1]} columns"
                        )
                        st.dataframe(df, use_container_width=True)
                    else:
                        st.json(data)
                except json.JSONDecodeError:
                    st.error("Invalid JSON file.")

            elif file_ext == "txt":
                content = uploaded.read().decode("utf-8", errors="replace")
                st.text_area(
                    "File contents",
                    value=content,
                    height=300,
                    disabled=True,
                )
        else:
            st.info("No file uploaded yet. Drag and drop or click **Browse files**.")

    # ── Download ─────────────────────────────────────────────────────────
    with download_tab:
        st.subheader("Generate & Download Files")
        st.markdown(
            "Streamlit's `st.download_button` lets you offer any in-memory "
            "data as a downloadable file."
        )

        # CSV download
        st.markdown("**1. Sample CSV**")
        sample_df = pd.DataFrame({
            "id": range(1, 11),
            "value": [round(i * 3.14, 2) for i in range(1, 11)],
            "label": [f"item_{i}" for i in range(1, 11)],
        })
        csv_bytes = sample_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="Download CSV",
            data=csv_bytes,
            file_name="sample_data.csv",
            mime="text/csv",
        )

        st.markdown("---")

        # JSON download
        st.markdown("**2. Session State Snapshot (JSON)**")
        st.caption(
            "This exports the current `st.session_state` as a JSON file — "
            "useful for debugging or auditing."
        )
        state_snapshot = {
            "exported_at": datetime.now().isoformat(),
            "keys": list(st.session_state.keys()),
            "sample_values": {
                k: str(v)[:200]
                for k, v in list(st.session_state.items())[:20]
            },
        }
        json_bytes = json.dumps(state_snapshot, indent=2).encode("utf-8")
        st.download_button(
            label="Download JSON",
            data=json_bytes,
            file_name="session_state_snapshot.json",
            mime="application/json",
        )

        st.markdown("---")

        # Plain text download
        st.markdown("**3. Custom Text Report**")
        report_text = st.text_area(
            "Type your report content below:",
            value="This is a sample report generated by the Streamlit demo app.",
            height=150,
            key="download_report_text",
        )
        st.download_button(
            label="Download TXT",
            data=report_text.encode("utf-8"),
            file_name="report.txt",
            mime="text/plain",
        )
